# permissions for end users to view chatgpts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chatgpt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aibot-controller
    app.kubernetes.io/part-of: aibot-controller
    app.kubernetes.io/managed-by: kustomize
  name: chatgpt-viewer-role
rules:
- apiGroups:
  - bot.kodecove.com
  resources:
  - chatgpts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bot.kodecove.com
  resources:
  - chatgpts/status
  verbs:
  - get
