---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bot.kodecove.com
  resources:
  - chatgpts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bot.kodecove.com
  resources:
  - chatgpts/finalizers
  verbs:
  - update
- apiGroups:
  - bot.kodecove.com
  resources:
  - chatgpts/status
  verbs:
  - get
  - patch
  - update
