//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotConfig) DeepCopyInto(out *BotConfig) {
	*out = *in
	in.BotCredentials.DeepCopyInto(&out.BotCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotConfig.
func (in *BotConfig) DeepCopy() *BotConfig {
	if in == nil {
		return nil
	}
	out := new(BotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotCredentials) DeepCopyInto(out *BotCredentials) {
	*out = *in
	in.TelgramToken.DeepCopyInto(&out.TelgramToken)
	in.OpenaiToken.DeepCopyInto(&out.OpenaiToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotCredentials.
func (in *BotCredentials) DeepCopy() *BotCredentials {
	if in == nil {
		return nil
	}
	out := new(BotCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chatgpt) DeepCopyInto(out *Chatgpt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chatgpt.
func (in *Chatgpt) DeepCopy() *Chatgpt {
	if in == nil {
		return nil
	}
	out := new(Chatgpt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Chatgpt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatgptList) DeepCopyInto(out *ChatgptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Chatgpt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatgptList.
func (in *ChatgptList) DeepCopy() *ChatgptList {
	if in == nil {
		return nil
	}
	out := new(ChatgptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChatgptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatgptSpec) DeepCopyInto(out *ChatgptSpec) {
	*out = *in
	in.DbConfig.DeepCopyInto(&out.DbConfig)
	in.BotConfig.DeepCopyInto(&out.BotConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatgptSpec.
func (in *ChatgptSpec) DeepCopy() *ChatgptSpec {
	if in == nil {
		return nil
	}
	out := new(ChatgptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatgptStatus) DeepCopyInto(out *ChatgptStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatgptStatus.
func (in *ChatgptStatus) DeepCopy() *ChatgptStatus {
	if in == nil {
		return nil
	}
	out := new(ChatgptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbConfig) DeepCopyInto(out *DbConfig) {
	*out = *in
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbConfig.
func (in *DbConfig) DeepCopy() *DbConfig {
	if in == nil {
		return nil
	}
	out := new(DbConfig)
	in.DeepCopyInto(out)
	return out
}
